version: '3.8'

services:
  criteriasearch:
    image: criteria-search
    build: .
    ports:
      - "8000-8999:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: criteriadb
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
